"""Prompt templates for identity-labeled critique."""

from identity_bias.config import IdentityCondition


# Identity-specific preambles (4 conditions)
IDENTITY_PREAMBLES = {
    IdentityCondition.SELF: (
        "Below is your previous solution to a problem. "
        "Please carefully review your own work."
    ),
    IdentityCondition.OTHER_MODEL: (
        "Below is a solution generated by another AI model. "
        "Please carefully review this solution."
    ),
    IdentityCondition.ANONYMOUS: (
        "Below is a solution to a problem. "
        "Please carefully review this solution."
    ),
    IdentityCondition.HUMAN: (
        "Below is a solution written by a human student. "
        "Please carefully review this solution."
    ),
}


CRITIC_SYSTEM_PROMPT = """You are a careful and rigorous reviewer of reasoning solutions. Your task is to determine whether a solution is correct and, if not, identify and fix errors.

You must respond in the following JSON format:
{{
    "is_correct": true or false,
    "error_description": "description of the error, or null if correct",
    "corrected_answer": "the correct final answer (your correction if there is an error, or the original answer if correct)",
    "confidence": 0.0 to 1.0
}}

Be thorough and precise. Only flag errors you are confident about."""


CRITIC_USER_PROMPT = """{identity_preamble}

**Problem:**
{question}

**Solution:**
{chain_of_thought}

**Final Answer:** {final_answer}

Please review this solution and respond with your assessment in the required JSON format."""


def build_critic_messages(
    question: str,
    chain_of_thought: str,
    final_answer: str,
    identity_condition: IdentityCondition,
) -> list[dict[str, str]]:
    """Build the message list for the critic LLM call."""
    preamble = IDENTITY_PREAMBLES[identity_condition]

    user_content = CRITIC_USER_PROMPT.format(
        identity_preamble=preamble,
        question=question,
        chain_of_thought=chain_of_thought,
        final_answer=final_answer,
    )

    return [
        {"role": "system", "content": CRITIC_SYSTEM_PROMPT},
        {"role": "user", "content": user_content},
    ]
